/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HumiditySensorFrCapteurDHumidity = "humidity";
export type LightSensorFrCapteurDeLuminosite = "light";
export type TemperatureSensorFrThermometre = "temperature";
export type AnalogInputs = {
  displayName: string;
  type: (HumiditySensorFrCapteurDHumidity | LightSensorFrCapteurDeLuminosite | TemperatureSensorFrThermometre) &
    string;
  index: number;

};
