/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type LightFrLumiere = "light";
export type OutletFrPrise = "outlet";
export type FanFrVentilation = "fan";
export type Valve = "valve";
export type Relays = {
  displayName: string;
  type: (LightFrLumiere | OutletFrPrise | FanFrVentilation | Valve) & string;
  index: number;

};
