/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MouvementSensorFrDetecteurDeMouvement = "motion";
export type SwitchFrInterrupteur = "switch";
export type ContactSensorFrContacteur = "contact";
export type Inputs = {
  displayName: string;
  type: (MouvementSensorFrDetecteurDeMouvement | SwitchFrInterrupteur | ContactSensorFrContacteur) & string;
  index: string;

};
