/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type IpxIp = string;
export type IpxApiKey = string;
export type IpxPollInterval = number;
export type IpxWebhookPort = number;
export type IpxWebhookPath = string;
export type IpxVersion = IpxVersion1 & IpxVersion2;
export type IpxVersion1 = V4 | V5;
export type V4 = "v4";
export type V5 = "v5";
export type IpxVersion2 = string;

export interface IpxApiConfiguration {
  ip?: IpxIp;
  key?: IpxApiKey;
  version?: IpxVersion;
  pollInterval?: IpxPollInterval;
  webhookPort?: IpxWebhookPort;
  webhookPath?: IpxWebhookPath;
  [k: string]: unknown;
}
